import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/redux/provider";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "./Components/Navbar";
export const metadata = {
  title: "BettingApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
